plugin:
    name: 'pensoft.library::lang.plugin.name'
    description: 'pensoft.library::lang.plugin.description'
    author: Pensoft
    icon: oc-icon-book
    homepage: ''
navigation:
    main-menu-item:
        label: Library
        url: pensoft/library/library
        icon: icon-book
        sideMenu:
            side-menu-records:
                label: Records
                url: pensoft/library/library
                icon: icon-book
            side-menu-targets:
                label: 'Target audiences'
                url: pensoft/library/targets
                icon: icon-users
